# Generated by Django 2.2 on 2020-01-23 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_annoucement_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoucement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.Course', verbose_name='Curso'),
        ),
    ]
